server:
  port: 8081

spring:
  application:
    name: pet-service
  datasource:
    url: jdbc:postgresql://localhost:5432/petsdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
